# Generated by Django 5.2.7 on 2025-10-12 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nome', models.CharField(default='', max_length=255)),
                ('telefone', models.CharField(default='', max_length=15)),
                ('cpf', models.CharField(default='', max_length=11, primary_key=True, serialize=False, unique=True)),
                ('profissao', models.CharField(default='', max_length=255)),
                ('renda_familiar', models.FloatField(default=0, max_length=10)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Divida',
            fields=[
                ('cod_divida', models.AutoField(primary_key=True, serialize=False)),
                ('cpf_funcionario', models.CharField(default='', max_length=11)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_divida', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Pendente', max_length=20)),
                ('num_notafiscal', models.CharField(default='', max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antiveaco.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='antiveaco.endereco'),
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('cod_pagamento', models.AutoField(primary_key=True, serialize=False)),
                ('data_pagamento', models.DateField(auto_now_add=True)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(default='Concluído', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antiveaco.cliente')),
                ('divida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antiveaco.divida')),
            ],
        ),
    ]
