# Generated by Django 5.2.7 on 2025-10-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cpf', models.CharField(default='', max_length=11, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('telefone', models.CharField(default='', max_length=15)),
                ('profissao', models.CharField(default='', max_length=100)),
                ('renda_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bairro', models.CharField(default='', max_length=100)),
                ('rua', models.CharField(default='', max_length=100)),
                ('numero', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
