# Generated by Django 5.2.7 on 2025-10-22 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antiveaco', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='status',
            new_name='status_cliente',
        ),
    ]
