# Generated by Django 5.2.7 on 2025-10-05 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiveaco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Divida',
            fields=[
                ('cod_divida', models.AutoField(primary_key=True, serialize=False)),
                ('cpf_funcionario', models.CharField(default='', max_length=11)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_divida', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Pendente', max_length=20)),
                ('num_notafiscal', models.CharField(default='', max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antiveaco.cliente')),
            ],
        ),
    ]
