# Generated by Django 5.2.7 on 2025-10-05 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiveaco', '0002_divida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('cod_compra', models.AutoField(primary_key=True, serialize=False)),
                ('data_compra', models.DateField(auto_now_add=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fiado', models.BooleanField(default=False)),
                ('status', models.CharField(default='Pendente', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antiveaco.cliente')),
                ('divida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='antiveaco.divida')),
            ],
        ),
    ]
