# Generated by Django 5.2.7 on 2025-10-05 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiveaco', '0003_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('cod_pagamento', models.AutoField(primary_key=True, serialize=False)),
                ('data_pagamento', models.DateField(auto_now_add=True)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(default='Concluído', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antiveaco.cliente')),
                ('divida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antiveaco.divida')),
            ],
        ),
    ]
