# Generated by Django 5.2.7 on 2025-10-10 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antiveaco', '0004_pagamento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compra',
        ),
    ]
